import React from 'react';
import { ChevronLeft, Play } from 'lucide-react';
import { motion } from 'motion/react';
import { ImageWithFallback } from './figma/ImageWithFallback';
import type { Course, RecentItem } from './podcast-types';

const SF = 'PodcastFigma, -apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", system-ui, sans-serif';

export function LibraryScreen({ courses, recentItems, onClose, onCourseSelect, onRecentPlay, activeLessonId }: { courses: Course[]; recentItems: RecentItem[]; onClose: () => void; onCourseSelect: (course: Course) => void; onRecentPlay: (courseId: string, lessonId: string) => void; activeLessonId?: string | null }) {
  return <div className="h-full overflow-x-hidden overflow-y-auto bg-[#f5f5f7] pb-28 text-[#1d1d1f]" style={{ fontFamily: SF }}>
    <div className="mx-auto max-w-[1440px] pt-14 lg:pt-12">
      <div className="px-5 sm:px-10 lg:px-16"><header className="mb-10 flex items-end justify-between"><div><button type="button" onClick={onClose} className="mb-5 flex items-center gap-1 text-[15px] font-semibold text-[#ff2d55]"><ChevronLeft size={18} />Flashcards</button><h1 className="text-[40px] font-bold leading-none tracking-[-.035em] sm:text-[54px]">Podcasts</h1></div></header><div className="mb-4"><h2 className="text-[22px] font-bold tracking-[-.025em]">Your Library</h2></div></div>
      <section className="flex gap-4 overflow-x-auto px-5 pb-8 sm:px-10 lg:px-16 custom-scrollbar">
        {courses.map((course) => <motion.button key={course.id} whileTap={{ scale: .975 }} onClick={() => onCourseSelect(course)} className="group shrink-0 w-[160px] text-left sm:w-[180px] lg:w-[200px]"><div className="relative aspect-square overflow-hidden rounded-[18px] bg-[#e5e5ea] shadow-[0_8px_20px_rgba(0,0,0,.1)] transition-transform duration-300 group-hover:-translate-y-1"><ImageWithFallback src={course.artwork} alt={course.title} className="size-full object-cover" /></div><p className="mt-3 truncate text-[17px] font-semibold tracking-[-.02em]">{course.title}</p><p className="mt-0.5 text-[14px] text-[#86868b]">{course.lessonCount} lessons · {course.totalDuration}</p></motion.button>)}
      </section>
      <div className="mt-6 px-5 sm:px-10 lg:px-16"><div className="mb-4"><h2 className="text-[22px] font-bold tracking-[-.025em]">Recently Played</h2></div><section className="grid gap-7 lg:grid-cols-[1.05fr_.95fr] lg:gap-12"><div><div className="overflow-hidden rounded-[20px] bg-transparent">{recentItems.map((item, index) => <button key={item.lessonId} onClick={() => onRecentPlay(item.courseId, item.lessonId)} className={`flex w-full items-center gap-4 py-3 text-left ${index ? 'border-t border-black/[.07]' : ''}`}><div className="relative size-[60px] shrink-0 overflow-hidden rounded-xl"><ImageWithFallback src={item.artwork} alt={item.courseName} className="size-full object-cover" />{activeLessonId === item.lessonId && <span className="absolute inset-0 grid place-items-center bg-black/35 text-white"><Play size={17} fill="currentColor" /></span>}</div><span className="min-w-0 flex-1"><span className={`block truncate text-[16px] ${activeLessonId === item.lessonId ? 'font-semibold text-[#ff2d55]' : 'font-semibold'}`}>{item.lessonTitle}</span><span className="mt-0.5 block truncate text-[14px] text-[#86868b]">{item.courseName}</span></span><Play size={20} fill="currentColor" /></button>)}</div></div><aside className="relative hidden min-h-[220px] overflow-hidden rounded-[24px] bg-[#19191b] p-7 text-white lg:block"><ImageWithFallback src={courses[0]?.artwork ?? ''} alt="" className="absolute inset-0 size-full object-cover opacity-35 blur-[1px]" /><div className="relative flex h-full flex-col justify-end"><p className="text-[13px] font-semibold uppercase tracking-[.1em] text-white/65">Continue learning</p><p className="mt-2 max-w-[260px] text-[28px] font-bold leading-[1.04] tracking-[-.03em]">Pick up where your listening left off.</p></div></aside></section></div>
    </div>
  </div>;
}
